version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis

    rabbitmq:
        image: rabbitmq:3-management

    orderdb:
        image: mcr.microsoft.com/mssql/server

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: src/Catalog/Catalog.API/Dockerfile
    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: src/Basket/Basket.Api/Dockerfile
    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: src/Ordering/Ordering.API/Dockerfile
    ocelotapigateway:
        image: ${DOCKER_REGISTRY-}ocelotapigateway
        build:
            context: .
            dockerfile: src/ApiGataway/OcelotAPIGateway/Dockerfile
    aspnetrunbasics:
        image: ${DOCKER_REGISTRY-}aspnetrunbasics
        build:
            context: .
            dockerfile: src/WebApp/AspnetRunBasics/Dockerfile

